/**
 * dsh-zcode-proxy browser half: client/index.js -> client.js
 *
 * Why a build step exists at all
 * ------------------------------
 * The host's client module system does not treat `exports["./client"]` as an
 * ES module. It reads the file and serves those bytes to the page as a plain
 * script, exactly like the bundled market-installer card, and expects the file
 * to hand its surface over itself:
 *
 *     window.__ModuleLoader__.load({ id, factory: (require) => { ... } })
 *
 * A bare ESM file therefore fails at the first token: the browser parses
 * `export const name = ...` as a script and throws
 *
 *     Uncaught SyntaxError: Unexpected token 'export'
 *
 * which the host reports as `dsh-zcode-proxy: import failed` and
 * `web boot: 1 entry did not activate` — the plugin's host half loads fine and
 * only the settings card is missing, so the failure looks unrelated to the
 * card. dsh-pocket-nas and dsh-mimo-connect both ship the wrapped form.
 *
 * The wrapper is intentionally hand-rolled rather than esbuild: this client has
 * no imports, no JSX and no dependency on React (it builds DOM with
 * `document.createElement`), so there is nothing for a bundler to resolve. The
 * script only rewrites the ESM export statements into assignments on the
 * factory's `exports` and wraps the result.
 *
 * Usage: node client/build.mjs   (wired to `npm run build:client`)
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const sourceDir = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(sourceDir, '..')
const sourcePath = resolve(sourceDir, 'index.js')
// `DSH_ZCODE_CLIENT_OUT` lets the test suite build to a scratch path and compare
// that against the committed artifact, instead of a "check" that rewrites the
// very file it is supposed to be verifying.
const outputPath = process.env.DSH_ZCODE_CLIENT_OUT
  ? resolve(process.env.DSH_ZCODE_CLIENT_OUT)
  : resolve(packageRoot, 'client.js')
const loaderId = process.env.DSH_ZCODE_CLIENT_ID ?? 'dsh-zcode-proxy'

const source = await readFile(sourcePath, 'utf8')

/**
 * Rewrite one `export` declaration into an assignment on the factory's
 * `exports`, keeping the declaration itself intact.
 *
 * `export const name = x` -> `const name = x` + `exports.name = name`
 * `export function apply(ctx) {}` -> `function apply(ctx) {}` + `exports.apply = apply`
 *
 * These are the only two shapes this file uses; anything else is refused loudly
 * rather than silently emitted as a broken bundle, so a future `export default`
 * or `export { a, b }` cannot ship a card that fails to load at runtime.
 *
 * @param {string} text
 * @returns {{ text: string, exported: string[] }}
 */
function rewriteExports(text) {
  const exported = []
  let out = text

  out = out.replace(/^export\s+const\s+([A-Za-z_$][\w$]*)\s*=/gm, (_match, name) => {
    exported.push(name)
    return `const ${name} =`
  })

  out = out.replace(/^export\s+function\s+([A-Za-z_$][\w$]*)\s*\(/gm, (_match, name) => {
    exported.push(name)
    return `function ${name}(`
  })

  const leftover = out.match(/^export\s+.+$/gm)
  if (leftover !== null) {
    throw new Error(
      `client/index.js uses an export form this build does not understand: ${leftover.join(' | ')}. ` +
        'Only `export const x =` and `export function x()` are supported.',
    )
  }

  if (exported.length === 0) {
    throw new Error('client/index.js declares nothing to export; the host would load an empty card')
  }

  return { text: out, exported }
}

const { text: rewritten, exported } = rewriteExports(source)

/**
 * The card is a React component, and `react` is provided by the host's client
 * module system through the factory's `require` — never a global, and not a
 * dependency of this package. Demanding it here means a source file that lost
 * its import fails the build instead of shipping a card that throws
 * `require is not defined` (or renders nothing) at runtime.
 */
if (!/require\(\s*['"]react['"]\s*\)/.test(source)) {
  throw new Error("client/index.js must obtain react via require('react'); the host provides it to the factory")
}

const assignments = exported.map((name) => `    exports.${name} = ${name};`).join('\n')

const bundle = `// Generated by client/build.mjs from client/index.js — do not edit by hand.
// The host serves this file to the page as a plain script, so it has to
// register itself with __ModuleLoader__; see client/build.mjs for why.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(loaderId)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;

${rewritten
  .split('\n')
  .map((line) => (line === '' ? '' : `    ${line}`))
  .join('\n')}

${assignments}
    return module.exports;
  }
});
`

await writeFile(outputPath, bundle, 'utf8')
console.log(`Wrote ${outputPath} (exports: ${exported.join(', ')})`)
